### ISSUE TITLE
Getting Error: "The JWT could not be decoded. Source: InvalidSignature" after creating a custom access token.

### ISSUE THREAD

**Issue by ArbazIrshad** [lpotthast/axum-keycloak-auth#31]
I have created an SPI that listens to user events and hit a protected API endpoint to respond to those events. I am creating a access token in the SPI and using that to create a request. But I am getting `{"error":"The JWT could not be decoded. Source: InvalidSignature"}`

This is the following method that I am using to create the access token: 

```java
 private String generateUserToken(String realmId, String userId) {

        final KeycloakContext context = session.getContext();
        final RealmModel realm = context.getRealm();
   
        final UserModel user = session.users().getUserById(realm, userId);
        final String clientId = context.getClient().getClientId();
     

        AccessToken token = new AccessToken();
        token.id(KeycloakModelUtils.generateId());

        token.type(TokenUtil.TOKEN_TYPE_BEARER);

        token.subject(userId);
    
        token.issuedNow();
        token.issuedFor(clientId);
        token.issuer(Urls.realmIssuer(context.getUri().getBaseUri(),
                context.getRealm().getName()));

        token.issuedNow();


        token.setPreferredUsername(user.getUsername());
        token.setGivenName(user.getFirstName());
        token.setFamilyName(user.getLastName());
        token.setEmail(user.getEmail());

        token.exp(token.getIat() + 360L);

        // return session.tokens().encode(token);



        // Get the active signing key
        KeyWrapper activeKey = session.keys().getActiveKey(realm, KeyUse.SIG, "RS256");

        String encodedToken = new JWSBuilder()
                .kid(activeKey.getKid())
                .type("JWT")
                .jsonContent(token)
                .sign(new AsymmetricSignatureSignerContext(activeKey));

        return encodedToken;

    }
```
What would be the best way to fix this?

**Comment by Tockra** [comment]
Hey ArbazIrshad,

I'm not familiar with the java libraries you used to create jwt. 
But you can log your JWT to console and use https://jwt.io/ to find out if everything is correct in the token itself.
If your keycloak server is public accessible the page should retrive the public key from your server and show you if the jwt is valid or not.

If this not work you have to visit <keycloak-url>/realms/<realm>/protocol/openid-connect/certs and you have to copy the whole json containg the kid mentioned in your jwt token on jwt.io. 
Then you copy this part to the public key area of "VERIFY SIGNATURE" :
![grafik](https://github.com/user-attachments/assets/7b092606-645a-449d-a41d-d2c872b41d92)

The most important part is the property "n" if this property contains the wrong value your jwt is marked as "invalid signature".


If this works and your token is correct, then you missconfigured the rust keycloak middleware. 
If this validation does not work, your problem is on token generation side.

**Comment by ArbazIrshad** [comment]
Hello @Tockra, 

Thanks for your detailed comment. I am just using the keycloak library to create a custom event listener.  But it looks like the issue was that I needed to start the server after creating the realm and setting up everything in keycloak. It looks like the issue is fixed now. I just need to set the emailVerified property too and now I can make a valid post request.
